### ISSUE TITLE
Geekworm X728 v2.1

### ISSUE THREAD

**Issue by NicciZar** [dincojazz/Geekworm_x750#1]
Hi,

Thank you for the addon.

Do you think this addon could be compatible with the the X728 v2.1?
If not would it be hard to implement the new board?

For its own software: https://wiki.geekworm.com/X728-Software

Hardware (with Pins used): https://wiki.geekworm.com/X728-hardware
on the Hardware site the pictures not showing the recent version. I can post pictures of it here if that's needed

Best regards

**Comment by NicciZar** [comment]
Okay so it seems like the X728 uses pin 3 and 5 for i2c and rtc

![image](https://user-images.githubusercontent.com/43537611/149672751-e87d935a-75d6-421d-a8dd-a0df38b170f1.png)

and the X750 from this integration seems to be also using 3 and 5

![image](https://user-images.githubusercontent.com/43537611/149672815-49fddd38-bf63-4972-9238-5b909092e569.png)

So this means I should be able to 'just' rename the X750 in your integration and it should hopefully work with the X728 (at least the battery voltage etc)


Links:
https://wiki.geekworm.com/index.php/X750
https://wiki.geekworm.com/X750_Hardware

**Comment by dincojazz** [comment]
Hi!
Sorry for late answer.
I think even if you don't rename it it will work.
The original addon was taken from Home Assistant Geekworm x720 Addon(from user Beduir ) https://github.com/Beduir/x720.git
And the only point to make renaming at his addon was just to see X750 model at my HA lovelace.
And it's working.
And I think if x728 using same pins for i2c it should work.
One advice: Be very careful with pin connecting Geekworm HAT to Pi. - DOUBLE CHECK plus, minus and i2c poles. It's very easy to burn Pi's i2c connection scheme. It's not a big deal, but after that my HA stopped showing X750 battery and capacity data.
Good luck!

**Comment by NicciZar** [comment]
Thank you for the reply!
My Pi is already connected with the UPS and seems to be running fine so it should be connected correctly I assume. 

Is your advice meant to be something I set on the software side also or only hardware (everything label minus to minus and plus to plus) and for the GPIO pins - its all a big block so I think I cannot change the layout here if that's needed

**Comment by dincojazz** [comment]
If you're stacking up Pi with X728 you can't make mistakes  because of 40 pin header.
X750 is with additional connector which is not 40 but 12 pins header and there everyone can make mistake. It's not fixed.

**Comment by NicciZar** [comment]
Alright. Yea I'm using the stack variant. Thank you!

**Comment by dincojazz** [comment]
I was "drinking water" from this well... :-)
https://community.home-assistant.io/t/greekworm-ups-hat/53059

**Comment by NicciZar** [comment]
I saw that. I am the last comment on that post haha 
Thats how I found out about this addon ;)

I'm a noob in GitHub repos. Is it correct that I "forked" your repo or do I have to go another way?

**Comment by dincojazz** [comment]
I'm a noob too.
I think it's not a problem "forking" the repo from me.
My is "forked" from Beduir's repo too.

**Comment by NicciZar** [comment]
Oh good. I was just hoping it didn't change the files in your Repo or something similar^^

**Comment by NicciZar** [comment]
Hey thanks for the help.

I've changed the stuff I needed to change (X750 to X728) and it seems to be working!
Capacity shows more than 100% (not sure why?) but I can live with that :D

Mains switched off:
![image](https://user-images.githubusercontent.com/43537611/149676585-c8f9af75-0009-4781-b36f-8cb77241877b.png)

![image](https://user-images.githubusercontent.com/43537611/149676592-80a1c99a-b02e-4f83-8853-8e40f3321743.png)

![image](https://user-images.githubusercontent.com/43537611/149676595-6435ff4f-3e00-4704-8dbb-a96c9c850f19.png)

**Comment by dincojazz** [comment]
Very good!
For the capacity...
Mine was the same at first about 10 days (if I remember right).
I think it's something like calibrating... or what...?
But now it's showing normaly...
![image](https://user-images.githubusercontent.com/75685324/149677001-c06a0eb5-b917-4363-91c9-fd72697bb470.png)
![image](https://user-images.githubusercontent.com/75685324/149677066-dd8c7f8d-52f0-4c31-bb84-417e6f389448.png)

**Comment by NicciZar** [comment]
Oh wow this looks really cool!

Do you have a script running that automatically uses the UPS (cuts main) or does the UPS automatically charge / discharge over time? 

I will let the UPS calibrate and hope it will then set to 100% when full

**Comment by dincojazz** [comment]
The UPS is automatically charging batteries at level of 4.1V and cuts charging at 4.2V.
You should not worry about the capacity... It's not a big deal.
The point is:
My set of HA is with Rpi3B+, mSATA 32GB and 3pc 30/30/10mm fans(the fans are consuming about 0.048A/hour) and the X750 is only with 2pc. 18650 3000mA batteries and it's holds it about 3 hours from 98% till 35% (in other words 63% from batteries for 3 hours)

**Comment by NicciZar** [comment]
Yea I saw the picture of the community forum. The case looks cool.

At the moment I only have the rpi4b and the ups connected with two 18650 2600mA (35A).
Which is overkill but I wanted to try it and now I can look out for other stuff.

-----

If you listen closely to the UPS do you hear some noise (except for the fans of course :D )? I hear a bit of noise which could be normal but I'm unsure

**Comment by dincojazz** [comment]
In my case I don't hear noises from UPS...
Do you have anything other around?
Check the power supply.
Is it working normally.
If you're using USB type C it should give to UPS minimum of 5V/3A. In case of jack it has to give 5V/4A.
Check the big resistors temperature with infrared thermometer for over heating.
Be careful not to hurt yourself.
In most of cases when I hear some noise of any electronic module (like bzzzzzz) it's coming from the power supply.
But that's not for shore.
Can't suggest anything else to help.
Sorry.

**Comment by dincojazz** [comment]
P.S.Check the power cable for good contact.

**Comment by NicciZar** [comment]
I think it was my power supply. I changed it to another one one and it seemed to have stopped.

Thanks for the suggestions!

**Comment by dincojazz** [comment]
I'm glad that you found the problem.
You're welcome!

**Comment by NicciZar** [comment]
Hi,
I just wanted to let you know its slowly calibrating itself

![image](https://user-images.githubusercontent.com/43537611/150102395-64d4ff78-b315-47b9-b783-d87ff795008b.png)

![image](https://user-images.githubusercontent.com/43537611/150102474-480b02f3-ae51-42d6-a037-6ab7c86f1230.png)


Thank you

Take care
