### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by bf8392** [dincojazz/Geekworm_x750#2]
Hi  =)

I can't find the add on in hacs....how can I install? And the knob is missing I think (to shut down and reboot)

**Comment by dincojazz** [comment]
Hi!
Installing is through custom components:
1.Coping files at directory config/custom components/x750/
2.Add at configuration.yaml:
sensor:
     - platform: x750
       name: 'RPi Battery'
3.Restart HA
4.Add entities at Dashboard
